# Generated by Django 6.0 on 2026-04-24 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot foydalanuvchi',
                'verbose_name_plural': 'Bot foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=150, verbose_name='Nomi (uz)')),
                ('name_ru', models.CharField(blank=True, default='', max_length=150, verbose_name='Nomi (ru)')),
                ('name_en', models.CharField(blank=True, default='', max_length=150, verbose_name='Nomi (en)')),
                ('gender', models.CharField(choices=[('erkak', 'Erkaklar'), ('ayol', 'Ayollar'), ('bola', 'Bolalar')], max_length=10, verbose_name="Bo'lim")),
                ('icon', models.CharField(blank=True, default='👕', max_length=10, verbose_name='Emoji/Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['gender', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=50, verbose_name='Rang (uz)')),
                ('name_ru', models.CharField(blank=True, default='', max_length=50, verbose_name='Rang (ru)')),
                ('name_en', models.CharField(blank=True, default='', max_length=50, verbose_name='Rang (en)')),
                ('hex_code', models.CharField(blank=True, default='', help_text='Masalan: #FF0000', max_length=7, verbose_name='HEX kodi')),
                ('emoji', models.CharField(blank=True, default='🔵', max_length=10, verbose_name='Emoji')),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name="O'lcham nomi")),
                ('size_type', models.CharField(choices=[('clothes', 'Kiyim (S, M, L, XL...)'), ('shoes', 'Oyoq kiyim (36, 37, 38...)'), ('kids', 'Bolalar (1-2 yosh, 3-4 yosh...)')], default='clothes', max_length=20, verbose_name='Turi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "O'lcham",
                'verbose_name_plural': "O'lchamlar",
                'ordering': ['size_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='main.botuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savatlar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Jami narx')),
                ('status', models.CharField(choices=[('yangi', '🆕 Yangi'), ('tasdiqlangan', '✅ Tasdiqlangan'), ('yetkazilmoqda', '🚚 Yetkazilmoqda'), ('yetkazildi', '📦 Yetkazildi'), ('bekor', '❌ Bekor qilingan')], default='yangi', max_length=20, verbose_name='Status')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, default='', verbose_name='Manzil')),
                ('note', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.botuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Nomi (uz)')),
                ('name_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Nomi (ru)')),
                ('name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Nomi (en)')),
                ('model_name', models.CharField(blank=True, default='', help_text='Masalan: Classic Fit, Slim Fit', max_length=100, verbose_name='Model nomi')),
                ('variant', models.CharField(blank=True, default='', help_text='Masalan: Premium, Standard', max_length=100, verbose_name='Variant')),
                ('description_uz', models.TextField(blank=True, default='', verbose_name='Tavsif (uz)')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Tavsif (ru)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Tavsif (en)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Dona narxi')),
                ('box_price', models.DecimalField(blank=True, decimal_places=0, help_text="Karobkada nechta dona bo'lsa, shu narx", max_digits=12, null=True, verbose_name='Karobka narxi')),
                ('box_quantity', models.PositiveIntegerField(default=1, help_text='1 karobkada nechta dona bor', verbose_name='Karobkadagi soni')),
                ('season', models.CharField(choices=[('bahor', 'Bahor'), ('yoz', 'Yoz'), ('kuz', 'Kuz'), ('qish', 'Qish'), ('universal', 'Universal')], default='universal', max_length=15, verbose_name='Mavsum')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Sotuvda bor')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Ombordagi soni')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Asosiy rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='Kategoriya')),
                ('colors', models.ManyToManyField(blank=True, related_name='products', to='main.productcolor', verbose_name='Ranglar')),
                ('sizes', models.ManyToManyField(blank=True, related_name='products', to='main.productsize', verbose_name="O'lchamlar")),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('color_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Rang')),
                ('size_name', models.CharField(blank=True, default='', max_length=20, verbose_name="O'lcham")),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Narx')),
                ('purchase_type', models.CharField(choices=[('dona', 'Donalik'), ('karobka', 'Karobkalik')], default='dona', max_length=10, verbose_name='Sotib olish turi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot rasmi',
                'verbose_name_plural': 'Mahsulot rasmlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('purchase_type', models.CharField(choices=[('dona', 'Donalik'), ('karobka', 'Karobkalik')], default='dona', max_length=10, verbose_name='Sotib olish turi')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.cart', verbose_name='Savat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Mahsulot')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.productcolor', verbose_name='Rang')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.productsize', verbose_name="O'lcham")),
            ],
            options={
                'verbose_name': 'Savat elementi',
                'verbose_name_plural': 'Savat elementlari',
            },
        ),
    ]
